In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('books.csv')

In [ ]:
df.head()

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1070 non-null   int64
 1   Publishing Year      1069 non-null   float64
 2   Book Name            1047 non-null   object
 3   Author               1070 non-null   object
 4   language_code        1017 non-null   object
 5   Author_Rating        1070 non-null   object
 6   Book_average_rating  1070 non-null   float64
 7   Book_ratings_count   1070 non-null   int64
 8   genre                1070 non-null   object
 9   gross sales          1070 non-null   float64
 10  publisher revenue    1070 non-null   float64
 11  sale price           1070 non-null   float64
 12  sales rank           1070 non-null   int64
 13  Publisher            1070 non-null   object
 14  units sold           1070 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 125.5+ KB

In [ ]:
df.isna().any()
#mengecek apakah ada data kosong
#jika True berarti ada
#jika False berarti tidak ada

index                  False
Publishing Year         True
Book Name               True
Author                 False
language_code           True
Author_Rating          False
Book_average_rating    False
Book_ratings_count     False
genre                  False
gross sales            False
publisher revenue      False
sale price             False
sales rank             False
Publisher              False
units sold             False
dtype: bool

In [ ]:
#hapus missing value
df = df.dropna()

In [ ]:
df.isna().any()

index                  False
Publishing Year        False
Book Name              False
Author                 False
language_code          False
Author_Rating          False
Book_average_rating    False
Book_ratings_count     False
genre                  False
gross sales            False
publisher revenue      False
sale price             False
sales rank             False
Publisher              False
units sold             False
dtype: bool

In [ ]:
#hapus kolom index, sales rank dan author rating
df = df.drop('index', axis=1)
df = df.drop('sales rank', axis=1)
df = df.drop('Author_Rating', axis=1)
df.head()

,Publishing Year,Book Name,Author,language_code,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,Publisher,units sold
0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,3.42,155903,genre fiction,34160.0,20496.0,4.88,HarperCollins Publishers,7000
1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,4.23,145267,genre fiction,12437.5,7462.5,1.99,HarperCollins Publishers,6250
2,2015.0,Go Set a Watchman,Harper Lee,eng,3.31,138669,genre fiction,47795.0,28677.0,8.69,"Amazon Digital Services, Inc.",5500
3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,4.04,150898,fiction,41250.0,24750.0,7.50,Hachette Book Group,5500
4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,4.04,198283,genre fiction,37952.5,22771.5,7.99,Penguin Group (USA) LLC,4750

In [ ]:
#supaya tidak ada.0 di publishing year
df['Publishing Year'] = df['Publishing Year'].fillna(0).astype(int)
df['Book_ratings_count'] = df['Book_ratings_count'].fillna(0).astype(int)
df['units sold'] = df['units sold'].fillna(0).astype(int)
df.head()

,Publishing Year,Book Name,Author,language_code,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,Publisher,units sold
0,1975,Beowulf,"Unknown, Seamus Heaney",en-US,3.42,155903,genre fiction,34160.0,20496.0,4.88,HarperCollins Publishers,7000
1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,4.23,145267,genre fiction,12437.5,7462.5,1.99,HarperCollins Publishers,6250
2,2015,Go Set a Watchman,Harper Lee,eng,3.31,138669,genre fiction,47795.0,28677.0,8.69,"Amazon Digital Services, Inc.",5500
3,2008,When You Are Engulfed in Flames,David Sedaris,en-US,4.04,150898,fiction,41250.0,24750.0,7.50,Hachette Book Group,5500
4,2011,Daughter of Smoke & Bone,Laini Taylor,eng,4.04,198283,genre fiction,37952.5,22771.5,7.99,Penguin Group (USA) LLC,4750

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 998 entries, 0 to 1069
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Publishing Year      998 non-null    int64
 1   Book Name            998 non-null    object
 2   Author               998 non-null    object
 3   language_code        998 non-null    object
 4   Book_average_rating  998 non-null    float64
 5   Book_ratings_count   998 non-null    int64
 6   genre                998 non-null    object
 7   gross sales          998 non-null    float64
 8   publisher revenue    998 non-null    float64
 9   sale price           998 non-null    float64
 10  Publisher            998 non-null    object
 11  units sold           998 non-null    int64
dtypes: float64(4), int64(3), object(5)
memory usage: 101.4+ KB

In [ ]:
df['genre'].value_counts(dropna=False)

genre
genre fiction    772
nonfiction       156
fiction           55
children          15
Name: count, dtype: int64

In [ ]:
df['genre'] = df['genre'].str.strip()
df['genre'] = df['genre'].str.replace('genre', '', case=False, regex=False)

In [ ]:
df.head()

,Publishing Year,Book Name,Author,language_code,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,Publisher,units sold
0,1975,Beowulf,"Unknown, Seamus Heaney",en-US,3.42,155903,fiction,34160.0,20496.0,4.88,HarperCollins Publishers,7000
1,1987,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,4.23,145267,fiction,12437.5,7462.5,1.99,HarperCollins Publishers,6250
2,2015,Go Set a Watchman,Harper Lee,eng,3.31,138669,fiction,47795.0,28677.0,8.69,"Amazon Digital Services, Inc.",5500
3,2008,When You Are Engulfed in Flames,David Sedaris,en-US,4.04,150898,fiction,41250.0,24750.0,7.50,Hachette Book Group,5500
4,2011,Daughter of Smoke & Bone,Laini Taylor,eng,4.04,198283,fiction,37952.5,22771.5,7.99,Penguin Group (USA) LLC,4750

In [ ]:
df['genre'].value_counts(dropna=False)

genre
fiction       827
nonfiction    156
children       15
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

Publishing Year        0
Book Name              0
Author                 0
language_code          0
Book_average_rating    0
Book_ratings_count     0
genre                  0
gross sales            0
publisher revenue      0
sale price             0
Publisher              0
units sold             0
dtype: int64

In [ ]:
df.to_csv('very_clean.csv', index=False)

from google.colab import files
files.download('very_clean.csv')